### ISSUE TITLE
License in the home page footer says MIT

### ISSUE THREAD

**Issue by romansp** [faisalman/ua-parser-js-docs#3]
Was checking out 2.0 announcement and noticed that license in the footer of the docs home page still says "Licensed under the MIT License". 

Sorry if it was intentional and supposed to mean that docs are MIT licensed and not the library itself. Thought this may be quite confusing to others.

**Comment by faisalman** [comment]
Ah yes, sorry about that! I forgot to update the license footer on the docs page. I'll update it soon.
